import { Component, OnInit, AfterViewInit, OnDestroy, signal, inject, ElementRef } from '@angular/core';
import { AnimationService } from '../../shared/services/animation.service';
import { UiButtonComponent } from '@shared/components/ui-button/ui-button.component';
import { TextRevealDirective } from '@shared/directives/text-reveal.directive';
import { LanguageService, type Lang } from '../../shared/services/language.service';
import { TranslationService } from '../../shared/services/translation.service';

/**
 * Données structurées pour la section Avant/Après.
 */
interface ComparisonEntry {
  readonly label: string;
  readonly withoutSwarm: string;
  readonly withSwarm: string;
  readonly improvement: string;
}

/**
 * Données structurées pour les piliers d'innovation.
 */
interface Pillar {
  readonly title: string;
  readonly description: string;
}

/**
 * Données structurées pour les limites du système.
 */
interface LimitCategory {
  readonly category: string;
  readonly items: readonly string[];
}

/**
 * Page Problème & Innovation — Composant pur Apple-grade.
 *
 * Présente la proposition de valeur de la Swarm à travers 6 sections
 * en plein écran avec animations au scroll.
 */

/* ==========================================================================
 * Données bilingues — Section 1 : Hero
 * ========================================================================== */

const HERO: Record<Lang, { title: string; subtitle: string }> = {
  fr: {
    title: 'Pourquoi la Swarm ?',
    subtitle: 'Le développement logiciel moderne est fractal : chaque fonctionnalité cache des dizaines de micro-décisions architecturales, de dépendances croisées et de cas limites. Les agents IA isolés savent écrire du code, mais échouent face à la complexité systémique des vrais projets. la Swarm change la donne.',
  },
  en: {
    title: 'Why the Swarm?',
    subtitle: 'Modern software development is fractal: every feature hides dozens of architectural micro-decisions, cross-dependencies, and edge cases. Isolated AI agents can write code, but fail against the systemic complexity of real projects. The Swarm changes the game.',
  },
};

/* ==========================================================================
 * Données bilingues — Section 2 : Avant/Après
 * ========================================================================== */

const COMPARISON_DATA: Record<Lang, ComparisonEntry[]> = {
  fr: [
    {
      label: 'Temps de développement',
      withoutSwarm: '3–5 jours pour une feature complète (spéculation, implémentation, tests, debug, documentation)',
      withSwarm: '15–45 minutes — le pipeline parallélise conception, code, tests et documentation',
      improvement: 'Jusqu\'à 160× plus rapide',
    },
    {
      label: 'Qualité du code',
      withoutSwarm: 'Revue humaine subjective, tests partiels, documentation déconnectée du code',
      withSwarm: 'Tests systématiques générés par un agent dédié, revue automatique par reviewer, documentation synchronisée',
      improvement: 'Couverture ≥ 80 %, zéro régression non détectée',
    },
    {
      label: 'Parallélisme',
      withoutSwarm: 'Un développeur = une tâche à la fois. Équipes bloquées par les dépendances',
      withSwarm: 'Agents front et back travaillent simultanément. Jusqu\'à 5 tâches indépendantes en parallèle',
      improvement: 'Débit ×5 sur les projets complexes',
    },
    {
      label: 'Documentation',
      withoutSwarm: 'Souvent obsolète avant même la fin du sprint. Écrite après coup, jamais prioritaire',
      withSwarm: 'Documentation générée automatiquement à chaque merge, toujours à jour, toujours en français',
      improvement: 'Docs vivantes, jamais obsolètes',
    },
  ],
  en: [
    {
      label: 'Development time',
      withoutSwarm: '3–5 days for a complete feature (speculation, implementation, testing, debugging, documentation)',
      withSwarm: '15–45 minutes — the pipeline parallelizes design, code, testing, and documentation',
      improvement: 'Up to 160× faster',
    },
    {
      label: 'Code quality',
      withoutSwarm: 'Subjective human review, partial testing, documentation disconnected from code',
      withSwarm: 'Systematic tests generated by a dedicated agent, automatic review by reviewer, synchronized documentation',
      improvement: 'Coverage ≥ 80%, zero undetected regressions',
    },
    {
      label: 'Parallelism',
      withoutSwarm: 'One developer = one task at a time. Teams blocked by dependencies',
      withSwarm: 'Front and back agents work simultaneously. Up to 5 independent tasks in parallel',
      improvement: '5× throughput on complex projects',
    },
    {
      label: 'Documentation',
      withoutSwarm: 'Often obsolete before the sprint ends. Written after the fact, never a priority',
      withSwarm: 'Documentation automatically generated on each merge, always up to date',
      improvement: 'Living docs, never obsolete',
    },
  ],
};

const COMPARISON_LABELS: Record<Lang, { withoutSwarm: string; withSwarm: string }> = {
  fr: { withoutSwarm: 'Sans la Swarm', withSwarm: 'Avec la Swarm' },
  en: { withoutSwarm: 'Without Swarm', withSwarm: 'With Swarm' },
};

/* ==========================================================================
 * Données bilingues — Section 3 : 7 piliers d'innovation
 * ========================================================================== */

const PILLARS: Record<Lang, Pillar[]> = {
  fr: [
    {
      title: 'Classification automatique de complexité',
      description: 'Le système évalue chaque tâche et la route sur le pipeline approprié : DIRECT, SIMPLE, ADAPT, MEDIUM ou FULL. Pas de configuration manuelle — la Swarm décide seul du niveau de rigueur nécessaire.',
    },
    {
      title: 'Routage intelligent à 5 niveaux',
      description: 'DIRECT pour les corrections triviales → SIMPLE pour les modifications ciblées → ADAPT pour les adaptations cross-cutting → MEDIUM pour les features multi-fichiers → FULL pour les fonctionnalités complexes avec contrats et gates.',
    },
    {
      title: 'Planification architecturale',
      description: 'Avant d\'écrire une ligne de code, un agent planner analyse l\'ensemble du codebase, détecte les fichiers impactés, identifie les patterns et conventions, et cartographie les dépendances. Le plan est validé par l\'humain avant exécution.',
    },
    {
      title: 'Implémentation parallèle front+back',
      description: 'Sur les tâches MEDIUM et FULL, les agents front et back travaillent simultanément. Le contract agent définit l\'interface (types + API) en amont, garantissant que les deux flux convergeront sans conflit.',
    },
    {
      title: 'Gates qualité automatisées',
      description: 'Chaque modification passe par deux gates : un agent tester génère et exécute les tests (seuil 80 % de couverture), puis un agent reviewer audite le code ET les tests avant d\'approuver ou de rejeter avec une liste précise des corrections nécessaires.',
    },
    {
      title: 'Intégration Git native',
      description: 'Le pipeline est pensé pour le workflow GitHub : une issue déclenche la création d\'une branche, la Swarm implémente, les gates valident, une PR est créée, et après revue humaine le merge est automatique. Zéro friction d\'intégration.',
    },
    {
      title: 'Documentation automatique',
      description: 'Après chaque merge, un agent writer met à jour le CHANGELOG, la documentation technique, le README et la proposition de valeur. La documentation est toujours synchronisée avec le code — elle n\'est jamais une corvée de fin de sprint.',
    },
  ],
  en: [
    {
      title: 'Automatic complexity classification',
      description: 'The system evaluates each task and routes it to the appropriate pipeline tier: DIRECT, SIMPLE, ADAPT, MEDIUM, or FULL. No manual configuration — the Swarm decides the level of rigor needed.',
    },
    {
      title: '5-level intelligent routing',
      description: 'DIRECT for trivial fixes → SIMPLE for targeted modifications → ADAPT for cross-cutting adaptations → MEDIUM for multi-file features → FULL for complex features with contracts and gates.',
    },
    {
      title: 'Architectural planning',
      description: 'Before writing a single line of code, a planner agent analyzes the entire codebase, detects impacted files, identifies patterns and conventions, and maps dependencies. The plan is validated by a human before execution.',
    },
    {
      title: 'Parallel front+back implementation',
      description: 'On MEDIUM and FULL tasks, front and back agents work simultaneously. The contract agent defines the interface (types + API) upfront, ensuring both streams converge without conflict.',
    },
    {
      title: 'Automated quality gates',
      description: 'Every change passes through two gates: a tester agent generates and runs tests (80% coverage threshold), then a reviewer agent audits both code AND tests before approving or rejecting with a precise list of required fixes.',
    },
    {
      title: 'Native Git integration',
      description: 'The pipeline is designed for GitHub workflow: an issue triggers branch creation, the Swarm implements, gates validate, a PR is created, and after human review, merge is automatic. Zero integration friction.',
    },
    {
      title: 'Automatic documentation',
      description: 'After each merge, a writer agent updates the CHANGELOG, technical documentation, README, and value proposition. Documentation is always synced with the code — never an end-of-sprint chore.',
    },
  ],
};

/* ==========================================================================
 * Données bilingues — Section 4 : Analyse des coûts
 * ========================================================================== */

const CLAUDE_COMPARISON_LABELS: Record<Lang, string[]> = {
  fr: [
    'Prix / mois (usage intensif)',
    'Modèle de tarification',
    'Pipeline automatisé (issue→PR→merge)',
    'Agents parallèles',
    'Gates qualité (tests + review)',
    'Intégration Git native',
    'Contexte maximum',
    'Déploiement automatisé',
    'Documentation auto',
    'Contrats TypeScript / OpenAPI',
  ],
  en: [
    'Price / month (intensive use)',
    'Pricing model',
    'Automated pipeline (issue→PR→merge)',
    'Parallel agents',
    'Quality gates (tests + review)',
    'Native Git integration',
    'Maximum context',
    'Automated deployment',
    'Auto documentation',
    'TypeScript / OpenAPI contracts',
  ],
};

const CLAUDE_COMPARISON_NOTE: Record<Lang, string> = {
  fr: 'Comparaison à juin 2026. Les tarifs Claude Pro/Max sont des abonnements fixes sans frais de token supplémentaires dans la limite des quotas. La Swarm fonctionne en API — vous ne payez que les tokens consommés, sans abonnement.',
  en: 'Comparison as of June 2026. Claude Pro/Max pricing is fixed subscriptions with no additional token fees within quota limits. The Swarm operates via API — you only pay for the tokens consumed, with no subscription.',
};

/* ==========================================================================
 * Données bilingues — Section 5 : Modèle d'IA
 * ========================================================================== */

const MODEL_INFO: Record<Lang, { description: string; strengths: string; costNote: string }> = {
  fr: {
    description: 'Modèle unique utilisé par tous les agents de la Swarm — orchestration, planification, implémentation front et back, tests, review et documentation.',
    strengths: 'Contexte de 1M tokens, raisonnement architectural, génération de code, analyse de codebase.',
    costNote: '0,435 $/M tokens en entrée (cache miss), 0,0036 $/M (cache hit), 0,87 $/M en sortie. Soit ~0,49 $/M effectif (65/35 input/output, 35% cache hit). Tarification API DeepSeek V4 Pro, juin 2026.',
  },
  en: {
    description: 'Single model used by all Swarm agents — orchestration, planning, front and back implementation, testing, review, and documentation.',
    strengths: '1M token context, architectural reasoning, code generation, codebase analysis.',
    costNote: '$0.435/M tokens input (cache miss), $0.0036/M (cache hit), $0.87/M output. ~$0.49/M effective (65/35 input/output, 35% cache hit). DeepSeek V4 Pro API pricing, June 2026.',
  },
};

/* ==========================================================================
 * Données bilingues — Section 6 : Limites du système
 * ========================================================================== */

const LIMITS: Record<Lang, LimitCategory[]> = {
  fr: [
    {
      category: 'Limites matérielles (hard limits)',
      items: [
        'Maximum 5 cycles par session — au-delà, le contexte devient trop lourd et la qualité se dégrade',
        'Maximum 5 tâches indépendantes en parallèle — limite dictée par la cohérence des résultats',
        'Tokens limités par le modèle (contexte maximum ~128 K tokens pour DeepSeek V4 Pro)',
      ],
    },
    {
      category: 'Limites architecturales',
      items: [
        'Pas de support pour les langages exotiques ou les frameworks obscurs — la Swarm s\'appuie sur la documentation disponible',
        'La qualité dépend de la planification initiale — un mauvais plan produit un mauvais résultat',
        'Pas de boucle de rétroaction après merge — chaque session est indépendante',
        'Pas de persistance de la mémoire entre sessions — chaque issue repart de zéro',
      ],
    },
    {
      category: 'Limites par agent',
      items: [
        'Planner : peut sous-estimer la complexité de tâches inhabituelles',
        'Front : limité par la qualité du contrat — si le contrat est incomplet, l\'agent est bloqué',
        'Back : inactif sur les projets statiques',
        'Reviewer : ne détecte pas les incohérences métier subtiles',
        'Writer : génère de la documentation technique, pas du contenu marketing',
      ],
    },
  ],
  en: [
    {
      category: 'Hardware limits',
      items: [
        'Maximum 5 cycles per session — beyond that, context becomes too heavy and quality degrades',
        'Maximum 5 independent tasks in parallel — limit dictated by result consistency',
        'Tokens limited by the model (maximum context ~128K tokens for DeepSeek V4 Pro)',
      ],
    },
    {
      category: 'Architectural limits',
      items: [
        'No support for exotic languages or obscure frameworks — the Swarm relies on available documentation',
        'Quality depends on initial planning — a bad plan produces a bad result',
        'No feedback loop after merge — each session is independent',
        'No memory persistence between sessions — each issue starts from scratch',
      ],
    },
    {
      category: 'Per-agent limits',
      items: [
        'Planner: may underestimate the complexity of unusual tasks',
        'Front: limited by contract quality — if the contract is incomplete, the agent is blocked',
        'Back: inactive on static projects',
        'Reviewer: does not detect subtle business inconsistencies',
        'Writer: generates technical documentation, not marketing content',
      ],
    },
  ],
};
@Component({
  selector: 'app-problem-innovation',
  standalone: true,
  imports: [UiButtonComponent, TextRevealDirective],
  templateUrl: './problem-innovation.component.html',
  styleUrls: ['./problem-innovation.component.scss'],
})
export class ProblemInnovationComponent implements OnInit, AfterViewInit, OnDestroy {
  /* ==========================================================================
   * Injection des services
   * ========================================================================== */

  private readonly animService = inject(AnimationService);
  private readonly hostRef = inject(ElementRef);
  private readonly langService = inject(LanguageService);
  private readonly translationService = inject(TranslationService);

  private get lang(): Lang { return this.langService.currentLang(); }

  /** Retourne la traduction pour la clé donnée dans la langue courante */
  t(key: string): string { return this.translationService.translate(key); }

  /* ==========================================================================
   * État du composant
   * ========================================================================== */

  /** Message d'erreur éventuel. */
  protected readonly error = signal<string | null>(null);

  /* ==========================================================================
   * Données — Section 1 : Hero
   * ========================================================================== */

  protected get heroTitle(): string { return HERO[this.lang].title; }
  protected get heroSubtitle(): string { return HERO[this.lang].subtitle; }

  /* ==========================================================================
   * Données — Section 2 : Avant/Après
   * ========================================================================== */

  protected get comparisonColumnLabels(): { withoutSwarm: string; withSwarm: string } {
    return COMPARISON_LABELS[this.lang];
  }

  protected get comparisonData(): readonly ComparisonEntry[] {
    return COMPARISON_DATA[this.lang];
  }

  /* ==========================================================================
   * Données — Section 3 : 7 piliers d'innovation
   * ========================================================================== */

  protected get pillars(): readonly Pillar[] {
    return PILLARS[this.lang];
  }

  /* ==========================================================================
   * Données — Section 4 : Analyse des coûts
   * ========================================================================== */

  protected get claudeComparisonRows(): readonly { label: string; swarm: string; claudePro: string; claudeMax: string }[] {
    const labels = CLAUDE_COMPARISON_LABELS[this.lang];
    const isFr = this.lang === 'fr';
    const values: readonly { swarm: string; claudePro: string; claudeMax: string }[] = [
      { swarm: '~8–25 $', claudePro: '20 $', claudeMax: '100–200 $' },
      { swarm: isFr ? 'Pay-per-token (DeepSeek V4 Pro)' : 'Pay-per-token (DeepSeek V4 Pro)', claudePro: isFr ? 'Abonnement fixe' : 'Fixed subscription', claudeMax: isFr ? 'Abonnement fixe' : 'Fixed subscription' },
      { swarm: '✅ Full auto', claudePro: '❌', claudeMax: '❌' },
      { swarm: isFr ? '✅ 9 agents + 2 utilitaires' : '✅ 9 agents + 2 utilities', claudePro: isFr ? '❌ Mono-agent' : '❌ Single-agent', claudeMax: isFr ? '❌ Mono-agent' : '❌ Single-agent' },
      { swarm: '✅ Tester + Reviewer', claudePro: isFr ? '❌ Aucune' : '❌ None', claudeMax: isFr ? '❌ Aucune' : '❌ None' },
      { swarm: '✅ Branche → PR → Merge', claudePro: '❌', claudeMax: '❌' },
      { swarm: '1M tokens (DeepSeek V4 Pro)', claudePro: '1M tokens (Opus 4.8, Sonnet 4.6)', claudeMax: '1M tokens (Opus 4.8, Sonnet 4.6)' },
      { swarm: '✅ Vercel + Render + Supabase', claudePro: isFr ? '❌ Manuel' : '❌ Manual', claudeMax: isFr ? '❌ Manuel' : '❌ Manual' },
      { swarm: '✅ CHANGELOG, README, ARCHITECTURE', claudePro: '❌', claudeMax: '❌' },
      { swarm: isFr ? '✅ Génération automatique' : '✅ Auto-generated', claudePro: '❌', claudeMax: '❌' },
    ];
    return labels.map((label, i) => ({ label, ...values[i] }));
  }

  protected get claudeComparisonNote(): string {
    return CLAUDE_COMPARISON_NOTE[this.lang];
  }

  /* ==========================================================================
   * Données — Section 5 : Modèle d'IA
   * ========================================================================== */

  protected readonly modelName = 'DeepSeek V4 Pro';

  protected get modelDescription(): string {
    return MODEL_INFO[this.lang].description;
  }

  protected readonly modelStrengths: readonly string[] = [
    'Contexte de 1M tokens',
    'Raisonnement architectural',
    'Génération de code',
    'Analyse de codebase',
  ];

  protected get modelCostNote(): string {
    return MODEL_INFO[this.lang].costNote;
  }

  /* ==========================================================================
   * Données — Section 6 : Limites du système
   * ========================================================================== */

  protected get limits(): readonly LimitCategory[] {
    return LIMITS[this.lang];
  }

  /* ==========================================================================
   * Lifecycle
   * ========================================================================== */

  ngOnInit(): void {
    this.initContent();
  }

  /** Méthode de retry — efface l'erreur. */
  protected retry(): void {
    this.error.set(null);
  }

  private initContent(): void {
    // Données statiques — aucune initialisation asynchrone nécessaire
  }

  ngAfterViewInit(): void {
    // Initialiser les animations au scroll après le rendu du DOM
    this.setupScrollAnimations();
  }

  ngOnDestroy(): void {
    this.animService.killAll();
  }

  /* ==========================================================================
   * Animations au scroll — GSAP (fallback CSS)
   * ========================================================================== */

  private async setupScrollAnimations(): Promise<void> {
    this.initScrollAnimations();
  }

  private async initScrollAnimations(): Promise<void> {
    try {
      const revealEls = this.hostRef.nativeElement.querySelectorAll('.reveal-on-scroll');

      if (revealEls.length > 0) {
        await this.animService.revealOnScroll(Array.from(revealEls), { staggerMs: 80 });
      }
    } catch {
      // Fallback CSS : révéler immédiatement
      const all = this.hostRef.nativeElement.querySelectorAll('.reveal-on-scroll');
      all.forEach((el: Element) => el.classList.add('revealed'));
    }
  }
}
